// Associationer 0-99. "alt" = alternativa associationer (visas under kortet;
// vald favorit sparas i localStorage). Bild: bilder/NN.png
const KORT = [
  { n: 0, namn: 'Pizza' },
  { n: 1, namn: 'Frihetsgudinnan' },
  { n: 2, namn: 'Zorro' },
  { n: 3, namn: 'Boomerang' },
  { n: 4, namn: 'Kartong' },
  { n: 5, namn: 'Stjärna' },
  { n: 6, namn: 'Sex', alt: ['Snöflinga'] },
  { n: 7, namn: 'Tärning' },
  { n: 8, namn: 'Snögubbe', alt: ['Spindel'] },
  { n: 9, namn: 'K9-hund', alt: ['Rubiks kub'] },
  { n: 10, namn: 'Kvinnan i röd klänning' },
  { n: 11, namn: '9/11', alt: ['Elvis'] },
  { n: 12, namn: 'Äggkartong' },
  { n: 13, namn: 'Svart katt' },
  { n: 14, namn: 'Hjärta' },
  { n: 15, namn: 'Moped' },
  { n: 16, namn: 'M16 (SWAT)', alt: ['Kettlebell'] },
  { n: 17, namn: 'Hackspett' },
  { n: 18, namn: 'Körkort' },
  { n: 19, namn: 'Covid' },
  { n: 20, namn: 'Cigaretter' },
  { n: 21, namn: 'Blackjack' },
  { n: 22, namn: 'Nixon' },
  { n: 23, namn: 'Jordan' },
  { n: 24, namn: 'Guldtacka 24K' },
  { n: 25, namn: 'Quarter Pounder' },
  { n: 26, namn: 'Födelsedagstårta' },
  { n: 27, namn: 'Nevermind-bebisen' },
  { n: 28, namn: 'Ounce 28 g' },
  { n: 29, namn: 'Leprechaun' },
  { n: 30, namn: 'Trisslott' },
  { n: 31, namn: 'Rumpan på bänken' },
  { n: 32, namn: 'Tänder' },
  { n: 33, namn: 'Wolverine' },
  { n: 34, namn: 'Pacman' },
  { n: 35, namn: 'Film' },
  { n: 36, namn: 'Roulette' },
  { n: 37, namn: 'Sjuk med termometer' },
  { n: 38, namn: 'Revolver .38' },
  { n: 39, namn: 'JAS 39 Gripen' },
  { n: 40, namn: 'Ali Baba & 40 rövare' },
  { n: 41, namn: 'Optimus Prime' },
  { n: 42, namn: 'Liftaren' },
  { n: 43, namn: 'Likör 43' },
  { n: 44, namn: 'Jeep 4x4' },
  { n: 45, namn: 'Atombomben' },
  { n: 46, namn: 'Svenska flaggan', alt: ['Telefon'] },
  { n: 47, namn: 'AK-47 (terrorist)' },
  { n: 48, namn: 'Eddie Murphy' },
  { n: 49, namn: 'Football' },
  { n: 50, namn: 'Skateboard 50-50' },
  { n: 51, namn: 'Area 51' },
  { n: 52, namn: 'Kalender (52 veckor)' },
  { n: 53, namn: 'Herbie' },
  { n: 54, namn: 'Studio 54' },
  { n: 55, namn: 'Applåd' },
  { n: 56, namn: 'Låsspray 5-56' },
  { n: 57, namn: 'Heinz 57' },
  { n: 58, namn: 'Svampbob' },
  { n: 59, namn: 'Hula (Hawaii)' },
  { n: 60, namn: 'Timer 60 sek' },
  { n: 61, namn: 'Gagarin' },
  { n: 62, namn: 'DNA-Nobelpriset' },
  { n: 63, namn: 'Kennedy' },
  { n: 64, namn: 'Schack', alt: ['Nintendo 64'] },
  { n: 65, namn: 'Guldklockan (pension)' },
  { n: 66, namn: 'Djävulen' },
  { n: 67, namn: 'Eleanor-Mustangen' },
  { n: 68, namn: 'Martin Luther King' },
  { n: 69, namn: '6ix9ine' },
  { n: 70, namn: 'Shrooms 70-tal' },
  { n: 71, namn: 'Nasdaq' },
  { n: 72, namn: 'Golf (par 72)' },
  { n: 73, namn: 'Sydneyoperan' },
  { n: 74, namn: '74-kanonskeppet' },
  { n: 75, namn: 'Bingo' },
  { n: 76, namn: 'Founding Fathers' },
  { n: 77, namn: 'Maxi 77' },
  { n: 78, namn: 'Jonestown' },
  { n: 79, namn: 'Smashing Pumpkins' },
  { n: 80, namn: 'Synthhår 80-tal' },
  { n: 81, namn: 'Hells Angels' },
  { n: 82, namn: 'Vulcan-hälsning' },
  { n: 83, namn: 'TI-83' },
  { n: 84, namn: 'Thomas' },
  { n: 85, namn: 'Oskar' },
  { n: 86, namn: 'Min födelse' },
  { n: 87, namn: 'Flatiron Building' },
  { n: 88, namn: 'Piano' },
  { n: 89, namn: 'Malin' },
  { n: 90, namn: 'Stridsbåt 90' },
  { n: 91, namn: '91:an' },
  { n: 92, namn: 'Bill Clinton' },
  { n: 93, namn: 'Saab 9-3' },
  { n: 94, namn: 'Brolin-gesten' },
  { n: 95, namn: 'Dolly Parton' },
  { n: 96, namn: 'Fåret Dolly' },
  { n: 97, namn: 'Prinsessan Diana' },
  { n: 98, namn: 'Windows 98' },
  { n: 99, namn: 'Gretzky' },
];
